### ISSUE TITLE
how can I get the builded project from another container

### ISSUE THREAD

**Issue by bublicov** [Hermsi1337/docker-composer#1]
Hi

Сan you suggest, how can I get the builded project on this container from another container ?

**Comment by Hermsi1337** [comment]
Hey @bublicov,
sorry for my late answer. 

TBH: I'm not sure, what your question is about. Do you want to use this `composer`-adaption for a project created with the "standard"-`composer` ?

**Comment by bublicov** [comment]
No, I wanted to build the project in one of the container and the finished project to copy into a container which is deploy on prod

as an option it can be done in Dockerfile with "COPY --from=compose:last ...."

**Comment by Hermsi1337** [comment]
Ahh, I see.   
Since `composer` requires a running PHP-environment in order to work properly I'd suggest to use a multi-stage dockerfile in order to build and deploy your application.

 For example:
```dockerfile
FROM     hermsi/alpine-composer:php7.2 as builder
COPY     your/local/files .
RUN      composer install

FROM     hermsi/alpine-fpm-php:7.2
COPY     --from=builder /app /var/www/html
```

I'd be glad to hear your feedback if that setup suits your needs.

**Comment by bublicov** [comment]
yes, I did it from the beginning, but it seemed to be not a clean decision

and I began to use gitlab, for multi-stage they have are special entities 'artifacts' that can be passed between containers

**Comment by Hermsi1337** [comment]
Using `gitlab-ci` with `artifcats` is also a good idea.   
I'd not say one solution is "better" then the other since both have there pro's and con's.

If you have access to a `Gitlab`-instance with a proper `CI-environment` I would also go for the `artifacts`-approach.
